### ISSUE TITLE
Guides lost formatting

### ISSUE THREAD

**Issue by djones** [refinery/website#10]
<img width="763" alt="screen shot 2017-07-18 at 8 22 19 am" src="https://user-images.githubusercontent.com/2478/28325371-7d34ef18-6b92-11e7-969a-d8741e94e053.png">

Here you can see a tip, warning and some code tags.

Each lack proper formatting. Tips and warnings should also have some sort of background colour applied so they don't look like a paragraph. Code blocks would be better if they had a light gray background.

**Comment by djones** [comment]
<img width="669" alt="screen shot 2017-07-18 at 8 31 30 am" src="https://user-images.githubusercontent.com/2478/28325750-8beb8e4e-6b93-11e7-8eaa-366943a79073.png">

"NOTE" is another message type which lost formatting.

**Comment by bricesanchez** [comment]
It's because we convert textile guides to markdown, we need to a QA: https://github.com/refinery/refinerycms/pull/3301

**Comment by bricesanchez** [comment]
BTW, thanks for your QA!
