### ISSUE TITLE
"Troubeshooting Image Problems" Formatting Issues

### ISSUE THREAD

**Issue by djones** [refinery/website#16]
<img width="624" alt="screen shot 2017-07-18 at 8 40 08 am" src="https://user-images.githubusercontent.com/2478/28326137-c7844404-6b94-11e7-964b-b9f1dec969ea.png">

^ that and the page is super super wide because an example under "Dragonfly.log" isn't breaking into multiple lines.

**Comment by bricesanchez** [comment]
fixed
