### ISSUE TITLE
"Full-Page Cache with Apache"

### ISSUE THREAD

**Issue by djones** [refinery/website#19]
<img width="420" alt="screen shot 2017-07-18 at 8 43 21 am" src="https://user-images.githubusercontent.com/2478/28326287-362207fc-6b95-11e7-8c24-9dd8186750fe.png">

<img width="782" alt="screen shot 2017-07-18 at 8 43 26 am" src="https://user-images.githubusercontent.com/2478/28326292-38ee12aa-6b95-11e7-93f9-ba268f2308f8.png">

**Comment by bricesanchez** [comment]
Fixed https://github.com/refinery/refinerycms/pull/3301/commits/10e93e9289faf01cd1afabd179e3f1f3fc5d77ff
