### ISSUE TITLE
Enable https for website

### ISSUE THREAD

**Issue by lanzhiheng** [refinery/website#23]
I think that wii be a good choice to enable HTTPS on website.  For free we can use https://letsencrypt.org/getting-started/ to get the certificate and renew it each 90 days.

**Comment by parndt** [comment]
Thanks - https://www.refinerycms.com is already encrypted with Let's Encrypt

**Comment by lanzhiheng** [comment]
@parndt Oh, I miss the https one, but I think it will be better to redirect http://www.refinerycms.com/ to https://www.refinerycms.com/ .

like this nginx config 

```
listen 80 default_server;
server_name refinery;
return 301 https://$host$request_uri
```

**Comment by parndt** [comment]
That is very valid @lanzhiheng !
