### ISSUE TITLE
S3 assets missing

### ISSUE THREAD

**Issue by parndt** [refinery/website#48]
@djones do you have any ideas? Seems like images are missing, e.g. if you to go https://www.refinerycms.com/blog

**Comment by djones** [comment]
Not totally sure who was hosting the S3 bucket. I haven't been able to find much reference to it. _But_ I do appear to have a backup of the contents of the bucket. So worst case we could create a new one. Looking into it...

**Comment by parndt** [comment]
Thanks! I'm not sure either, it's pretty weird!

**Comment by djones** [comment]
Created a new bucket and restored from backup. Should be good to close this issue now.

**Comment by bricesanchez** [comment]
Thank you very much @djones !

**Comment by parndt** [comment]
Thanks, Dave! :clap:
