### ISSUE TITLE
Trademark notice is missing

### ISSUE THREAD

**Issue by djones** [refinery/website#6]
Something like this would be acceptable: "Copyright © 2017 Refinery CMS. Refinery CMS a trademark of Resolve Digital."

**Comment by djones** [comment]
Weirdly the output is ```Copyright © 2017 Refinery CMS.<br> Refinery CMS™ is a trademark of Resolve Digital.``` there's a `<br>` in there.

**Comment by bricesanchez** [comment]
Sorry, i didn't check the footer after the quick fix.
