### ISSUE TITLE
Last commit message on home page is misleading

### ISSUE THREAD

**Issue by djones** [refinery/website#7]
It says "Updated about 3 hours ago by Philip Arndt." but as far as I can tell it's been longer than that.

I would suggest removing that feature completely. It's not very useful. If folks want to accurately get a pulse on the project, they should look here https://github.com/refinery/refinerycms/pulse which gives you a much better idea.

**Comment by djones** [comment]
Looks like the time might be accurate but not based on master which is what it clicks through to, so that's a bit confusing.

I would remove it anyway.

**Comment by bricesanchez** [comment]
I will think about that, i like the fact to see the project is actively maintained but i understand your concern: at this time it only display the work of a team member and not the community. I could be improve or remove.

**Comment by parndt** [comment]
Perhaps we should just give a date/time for when it was last updated rather than using time ago in words?
