### ISSUE TITLE
"Showcase" is nested under "Tour"

### ISSUE THREAD

**Issue by djones** [refinery/website#9]
Why do we force the user to go inside "Tour" to get to "Showcase" when there's nothing else under "Tour"?

I would suggest just removing "Tour" and having "Showcase" as top level navigation.

**Comment by bricesanchez** [comment]
It's nested because i would like re-create the About page and a feature page.

**Comment by parndt** [comment]
Until such time as those pages exist, I've removed the nesting. :+1:
